version: '3.9'
services:
  web:
    image: nginx:latest
    # ports:
    #   - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${APP_NAME}-http.rule=Host(`${APP_DOMAIN}`)"
        - "traefik.http.routers.${APP_NAME}-http.entrypoints=web"
        - "traefik.http.routers.${APP_NAME}-http.middlewares=https_redirect"
        - "traefik.http.routers.${APP_NAME}-http.service=${APP_NAME}-service"
        - "traefik.http.routers.${APP_NAME}-https.rule=Host(`${APP_DOMAIN}`)"
        - "traefik.http.routers.${APP_NAME}-https.entrypoints=websecure"
        - "traefik.http.routers.${APP_NAME}-https.middlewares=app-compress"
        - "traefik.http.routers.${APP_NAME}-https.tls=true"
        - "traefik.http.routers.${APP_NAME}-https.tls.certresolver=lets-encrypt"
        - "traefik.http.routers.${APP_NAME}-https.service=${APP_NAME}-service"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.server.port=80"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.healthcheck.path=/health-check"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.healthcheck.port=80"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.healthcheck.hostname=${APP_DOMAIN}_web"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.healthcheck.interval=60s"
        - "traefik.http.services.${APP_NAME}-service.loadbalancer.healthcheck.timeout=5s"
        - "traefik.http.middlewares.app-compress.compress=true"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      placement:
        constraints:
          - "node.labels.app==${DOCKER_APP}"
          - "node.labels.role==${DOCKER_ROLE}"